In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## What is PCA and Where to use it?
- **PCA (Principal Component Analysis)** is a mathematical technique of adjusting the data dimensions in a way that some of the first dimension or first principal componenet (PC1, PC2, PC3 etc) will hold large infomration or Eigen Value of the entire dataset as compared to last dimension or last principal components (PCn-3, PCn-2, PCn-1, PCn).

- Where to use?
    - Feature reduction - If we are dealing with the very high dimensional dataset we can reduce the features by utilizing some of the top principal components holding high Eigen Values.
    - Identifying Clusters 
    - Representation of high dimenstional data 

In [8]:
data = pd.read_csv("Sythetic_Correlated_Data.csv")
data.head()

,Feature_1,Feature_2,Feature_3
0,0.496714,0.285743,-0.339434
1,-0.138264,-0.486851,0.104366
2,0.647689,1.124020,-0.093872
3,1.523030,2.644921,-0.518793
4,-0.234153,-0.548950,-0.206065


## Let's visualize 3 dimensions of data

In [26]:
# plot 3d scatter plot using go library
import plotly.graph_objects as go

fig = go.Figure(data=[go.Scatter3d(
    x=data['Feature_1'],
    y=data['Feature_2'],
    z=data['Feature_3'],
    mode='markers',
    marker=dict(size=3, color='blue')
)])
fig.update_layout(
    height=800,  # increase vertical size (default ~450)
    scene=dict(
        xaxis_title='Feature 1',
        yaxis_title='Feature 2',
        zaxis_title='Feature 3'
    )
)

## Compute mean of each feature, in our case there are three features so we will have three means

In [27]:
# Compute mean of each feature, in our case there are three features so we will have three means
mean_vector = np.mean(data, axis=0)
print("Mean Vector:\n", mean_vector)

Mean Vector:
 Feature_1   -0.103847
Feature_2   -0.196541
Feature_3    0.057864
dtype: float64


In [31]:
# Now shift the data by subtracting the mean vector from each data point
centered_data = data - mean_vector
centered_data.head()

# Show the 3D scatter plot of the centered data with the mean vector at the origin
fig_centered = go.Figure(data=[go.Scatter3d(
    x=centered_data['Feature_1'],
    y=centered_data['Feature_2'],
    z=centered_data['Feature_3'],
    mode='markers',
    marker=dict(size=3, color='blue')
)])
fig_centered.update_layout(
    height=800,
    scene=dict(
        xaxis_title='Feature 1 (Centered)',
        yaxis_title='Feature 2 (Centered)',
        zaxis_title='Feature 3 (Centered)'
    )
)
fig_centered.add_trace(go.Scatter3d(
    x=[0],
    y=[0],
    z=[0],
    mode='markers',
    marker=dict(size=10, color='red'),
    name='Mean Vector (Origin)'
))
fig_centered.update_layout(title='3D Scatter Plot of Centered Data')
fig_centered.show()

## Compute the best fit line on the datapoints

In [ ]:
U, S, Vt = np.linalg.svd(centered_data, full_matrices=False)
best_fit_direction = Vt[0]
print("Best Fit Direction (Principal Component 1):\n", best_fit_direction)

Best Fit Direction (Principal Component 1):
 [-0.43644333 -0.886728    0.15241615]


In [34]:
# Show the best fit direction as a line in the 3D scatter plot of the centered data
fig_centered.add_trace(go.Scatter3d(
    x=[0, best_fit_direction[0] * 5],  # Scale the line for better visualization
    y=[0, best_fit_direction[1] * 5],
    z=[0, best_fit_direction[2] * 5],
    mode='lines',
    line=dict(color='green', width=5),
    name='Best Fit Direction (PC1)'
))
fig_centered.update_layout(title='3D Scatter Plot of Centered Data with Best Fit Direction')
fig_centered.show()

# Now compuate the unite vector (EigenVector)

In [35]:
# Now compuate the unite vector (EigenVector)
eigenvector_1 = best_fit_direction / np.linalg.norm(best_fit_direction)
print("Unit EigenVector (Principal Component 1):\n", eigenvector_1)

Unit EigenVector (Principal Component 1):
 [-0.43644333 -0.886728    0.15241615]


In [36]:
# Show eigenvector as a line in the 3D scatter plot of the centered data
fig_centered.add_trace(go.Scatter3d(
    x=[0, eigenvector_1[0] * 5],  # Scale the line for better visualization
    y=[0, eigenvector_1[1] * 5],
    z=[0, eigenvector_1[2] * 5],
    mode='lines',
    line=dict(color='orange', width=5),
    name='Unit EigenVector (PC1)'
))
fig_centered.update_layout(title='3D Scatter Plot of Centered Data with EigenVector')
fig_centered.show()

## Now calculate PC2 which is the second best fit direction

In [38]:
# Now calculate PC2 which is the second best fit direction
best_fit_direction_2 = Vt[1]
eigenvector_2 = best_fit_direction_2 / np.linalg.norm(best_fit_direction_2)
print("Unit EigenVector (Principal Component 2):\n", eigenvector_2)

Unit EigenVector (Principal Component 2):
 [ 0.4233106  -0.35185386 -0.83486945]


In [39]:
# Show first and second eigenvectors as lines in the 3D scatter plot of the centered data
fig_centered.add_trace(go.Scatter3d(
    x=[0, eigenvector_2[0] * 5],  # Scale the line for better visualization
    y=[0, eigenvector_2[1] * 5],
    z=[0, eigenvector_2[2] * 5],
    mode='lines',
    line=dict(color='purple', width=5),
    name='Unit EigenVector (PC2)'
))
fig_centered.update_layout(title='3D Scatter Plot of Centered Data with EigenVectors')
fig_centered.show()

## Now let's show first, second and third eigenvectors together in the 3D scatter plot of the centered data

In [40]:
# Now let's show first, second and third eigenvectors together in the 3D scatter plot of the centered data
eigenvector_3 = Vt[2] / np.linalg.norm(Vt[2])
print("Unit EigenVector (Principal Component 3):\n", eigenvector_3)
fig_centered.add_trace(go.Scatter3d(
    x=[0, eigenvector_3[0] * 5],  # Scale the line for better visualization
    y=[0, eigenvector_3[1] * 5],
    z=[0, eigenvector_3[2] * 5],
    mode='lines',
    line=dict(color='cyan', width=5),
    name='Unit EigenVector (PC3)'
))
fig_centered.update_layout(title='3D Scatter Plot of Centered Data with All EigenVectors')
fig_centered.show()

Unit EigenVector (Principal Component 3):
 [-0.79393032  0.29985383 -0.52892563]


## How show the % information retained by each principal component using scree plot with go library

In [42]:
# How show the % information retained by each principal component using scree plot with go library
explained_variance = S**2 / np.sum(S**2)
fig_scree = go.Figure(data=[go.Bar(
    x=['PC1', 'PC2', 'PC3'],
    y=explained_variance,
    marker=dict(color=['orange', 'purple', 'cyan'])
)])
fig_scree.update_layout(title='Scree Plot', xaxis_title='Principal Components', yaxis_title='Explained Variance Ratio')
fig_scree.show()

In [44]:
explained_variance

array([0.96932334, 0.02659799, 0.00407867])

## Now let's plot PC1 and PC2 as a 2D scatter plot to see how much variance is retained in the first two principal components

In [47]:
# Now let's plot PC1 and PC2 as a 2D scatter plot to see how much variance is retained in the first two principal components
pc1_scores = centered_data @ eigenvector_1
pc2_scores = centered_data @ eigenvector_2
fig_pc = go.Figure(data=[go.Scatter(
    x=pc1_scores,
    y=pc2_scores,
    mode='markers',
    marker=dict(size=3, color='blue')
)])
fig_pc.update_layout(title='2D Scatter Plot of PC1 vs PC2', xaxis_title='Principal Component 1', yaxis_title='Principal Component 2')
fig_pc.show()